### ISSUE TITLE
Getting "Error in t/bin_length : non-numeric argument to binary operator" for several functions

### ISSUE THREAD

**Issue by pubhatta** [rethomics/zeitgebr#12]
Hi,

I've created my behavr table from my metadata and data files, which are structured very similarly to the examples in the behavr tables tutorial. However, I've tried visualizing the data using ggetho - stat_tile_etho() and stat_bar_tile_etho(), and I've tried computing a chi square periodogram and each time I get this error: 

"Error in t/bin_length : non-numeric argument to binary operator"

I made sure that my 't' column is numeric and the values are in seconds (as shown in the tutorial examples), and I assume 'bin_length' is a variable somewhere within the function's code, so I'm not sure where the 'non-numeric argument' is coming from. I even specified the sampling rate in the periodogram method, but it didn't make a difference. The only code I was able to run was when I specifically ran the "chi_sq_periodogram" function on just the activity column, but this only gives me one observation for each period, rather than observations for each period in each subject's data. 

My data, metadata and code files are in the link below:
https://github.com/pubhatta/zeitgebr_issue

Any help fixing this issue is appreciated!

**Comment by qgeissmann** [comment]
Hey, thanks for reporting. just sent you a pull request (https://github.com/pubhatta/zeitgebr_issue/pull/1). Main issue is time should be named `t`, not `time`. Also other issues with some variable names such as `uid` that are not there (that you need to make yourself to describe individuals in a more informative way than a number). I hope it helps. If all done, feel free to close

**Comment by pubhatta** [comment]
Thanks for the response. Regarding uid , does this make a difference in terms of the code working? I can see how a more descriptive id is beneficial for being more informative, but since my data came formatted with numbers for id's and the tutorial recommends assigning numeric uid's to help with plotting, I figured I could skip that step because my id's are already numeric.  Why would this affect the functioning of the code?

**Comment by pubhatta** [comment]
Never mind, I just realized that uid is used in the facet_wrap() argument! Must have missed that earlier.

**Comment by pubhatta** [comment]
One last question - I know that the argument `sampling_rate` is an argument of the `FUN=chi_sq_periodogram` , not an argument of `periodogram()` itself. I added that argument after the FUN argument because I wanted to specify that the sampling rate of the data was 1/hour, and in the `periodogram()` documentation it says that arguments to be passed to FUN should follow the FUN argument. I don't want to resample the data, so I don't think it makes sense to use that argument instead. Am I wrong in this reasoning?
