### ISSUE TITLE
Question about resample_rate argument in periodogram()

### ISSUE THREAD

**Issue by pubhatta** [rethomics/zeitgebr#13]
I'm a little confused as to what the `resample_rate` argument does in the `periodogram()` function, and how/if I should use it. My data is sampled at 1 reading per hour. When I set `resample_rate=1/hours(1)`, the resolution I get on the periodogram is much lower than when I leave out the resample_rate argument. In other words, it outputs the same "power" for many more consecutive periods, so the plot looks more "blocky", making it more difficult to discern differences between conditions. I've attached two plots below to describe what I'm talking about. The top one is with resampling, the bottom one is without.

![periodogram_all_resample](https://user-images.githubusercontent.com/63832899/79616138-45c13980-80d2-11ea-98be-b5d9649f4757.png)
![periodogram_all_condition](https://user-images.githubusercontent.com/63832899/79616136-4528a300-80d2-11ea-9549-e9ea2d9f9e36.png)

My main question is, is it really necessary for me to include the resample_rate argument (considering that my data is sampled at 1/hour)? I'm not familiar with the reasoning behind resampling the data or how and when to do it, I only included it because I thought I needed to specify the sampling rate at which the data was collected, in case it's not the default sampling rate assumed by the function. I would much rather have periodogram plots with better resolution (like the ones I'm getting without including the resampling_rate argument), but I want to make sure leaving it out isn't incorrect for how my data is structured.

**Comment by pubhatta** [comment]
Hi, again! I would greatly appreciate any help with this question. All I really need to know whether it's appropriate to **not** include the `resample_rate` argument in the `periodogram()` function if my data is sampled at 1/hour. Since it gives better resolution on the periodogram when I leave it out, I would prefer not to include it, especially since it's not used in any of the standard examples in the tutorial or documentation. However, I just want to make sure that leaving it out is acceptable and appropriate given my sampling rate.

**Comment by qgeissmann** [comment]
Hi @pubhatta, the argument can technically not be 'taken out'. Indeed, it has a default value of 1/mins(15) -- 15 minutes. That means *your data is actually resampled* (linearly interpolated). In between the points you have. Resampling is built-in since we have been working a lot with irregular time series or time series with a few missing data points. This ensures the processed time series are regular. My sense is that, in your case, the resampled time series could be used to estimate peak frequency and compare peaks between multiple individuals. (as opposed to considering a time point as an individual -- in which case you are artificially pseudoreplicating your own data). Does it make sense?

**Comment by pubhatta** [comment]
Sorry, I should have clarified - I already figured that there is likely a default resampling rate if I don't specify otherwise. The interpolation makes sense, especially since I want a precision greater than the sampling rate for the periodogram results. Thanks for clarifying that. I do want to compare period length between multiple individuals, so this works out for me. 

I really meant to ask whether I need to specify `resampling_rate=1/hours(1)` within the code due to the fact that my original sampling rate is 1/hour. On second thought, it doesn't really make sense to "resample" at the same rate the data was collected at, but I thought I was supposed to because I thought the resampling_rate argument in the main periodogram() function is a substitute for the sampling_rate argument in the chi_sq_periodogram() function. 

So just to be clear, it is okay to go with the default resampling rate of 1/mins(15) regardless of the sampling rate my data was collected at, correct?

**Comment by qgeissmann** [comment]
yes, sorry if it was not clear :). The functions used by `periodogram()` (e.g. `chi_sq_periodogram()`) need a regular sampling frequency, the `periodogram()` function preprocessed the time series to force it to have this frequency (if it is the same as the original sampling frequency, it would have ~ no effect). In short, 'chi_sq_periodogram' internally uses `resampling_rate` (and does not see the original signal.)

**Comment by pubhatta** [comment]
Great, thanks for clearing that up!
