### ISSUE TITLE
Error on Lomb::lsp when data is a series of zeros

### ISSUE THREAD

**Issue by pepelisu** [rethomics/zeitgebr#2]
The function periodogram does not check for dead animals, or for series that are full of ceros. When that series is fed to the lomb::lsp function it complains with:  
 ```
Error in if (p > 0.01) p <- 1 - (1 - exPN)^effm : 
  missing value where TRUE/FALSE needed 
```

**Comment by qgeissmann** [comment]
maybe we should raise a warning and fill the periodogram values with NA when there `length(unique(x)) <2`
